name: Publish new theme version
on:
  push:
    tags: # Sequence of patterns matched against refs/tags
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2 26-01
      - name: Bundle
        id: bundle
        run: |
          ls
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT
      - name   	: Create Release
        id     	: create_release
        uses   	: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b #2.5.0 2
        if     	: github.ref_type == 'tag'
        with   	:
          files	:	|
                  manifest.json
                  theme.css
          fail_on_unmatched_files: true
          preserve_order	: false #order of files should be preserved when uploading assets
          tag_name      	: ${{ github.ref }}
          name          	: ${{ github.ref_name }}
          draft         	: false
          prerelease    	: false
        env             	:
          GITHUB_TOKEN  	: ${{ secrets.Release }}
          VERSION       	: ${{ github.ref      }}
